# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AscMcp < Formula
  desc "MCP server for App Store Connect metadata, products, pricing, screenshots and submission"
  homepage "https://github.com/tergeoo/asc-mcp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tergeoo/asc-mcp/releases/download/v0.1.0/asc-mcp_0.1.0_darwin_amd64.tar.gz"
      sha256 "ab870a6f228b9cf79aaa43fc75d19d0dd8c43e0145b8ec4e225d05d6f097f047"

      define_method(:install) do
        bin.install "asc-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tergeoo/asc-mcp/releases/download/v0.1.0/asc-mcp_0.1.0_darwin_arm64.tar.gz"
      sha256 "aafd01e1dd3cba668f46fcca80af7e203f30daae5581352fd29b4797b2900869"

      define_method(:install) do
        bin.install "asc-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tergeoo/asc-mcp/releases/download/v0.1.0/asc-mcp_0.1.0_linux_amd64.tar.gz"
      sha256 "fbb4d2a8135821dcd4264eec1672f8d6e6f6255e0ee9536347a52ce357d43cec"
      define_method(:install) do
        bin.install "asc-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tergeoo/asc-mcp/releases/download/v0.1.0/asc-mcp_0.1.0_linux_arm64.tar.gz"
      sha256 "ed3d6dbaa980df152d984ffca496a23d08d99fddd21d1d6b4da923dd0618867e"
      define_method(:install) do
        bin.install "asc-mcp"
      end
    end
  end

  test do
    system "#{bin}/asc-mcp", "-version"
  end
end
